### ISSUE TITLE
Accession number same as contig name.

### ISSUE THREAD

**Issue by caonetto** [NBISweden/EMBLmyGFF3#27]
Hi,
I am trying to use this tool to make an embl file for upload to IMG, however I am having issues with the output. First thing, is there a way to assign ID as the contig name?, in IMG they dont accept files with XXX as id name. 
Thanks

**Comment by Juke34** [comment]
What I understand your purpose is not the submission to the ENA database but the creation of an EMBL file for a tool called IMG. 

Instead of having 
`ID   XXX; XXX; linear; genomic DNA; XXX; INV; 1351857 BP.
XX
AC   XXX; 
XX
AC * chr_1`

you would like an option to get:
`
ID   chr_1; XXX; linear; genomic DNA; XXX; INV; 1351857 BP.
XX
AC   chr_1;
XX
AC * chr_1`
`

**Comment by caonetto** [comment]
Thanks for your reply. I had to replace the XXX values from the accession line that are meant to be filled up by ENA as this is incompatible with the JGI (Joint genome institute) upload pipeline. It might be a good idea to include this in the option parameters?

Thanks.

**Comment by Juke34** [comment]
I have modified the `-a --accession` option. It made no sense to be able to provide a value, because each record in the EMBL file would have a different accession number. So I have modified it to be a bolean. If you activate it, for each record the sequence name from the fasta file would become the accession.

Then, if the extra line `AC * _chr1` needed for submission is problematic for your purpose, removing it using a `sed` command must be fine.
