### ISSUE TITLE
question: what additional options for mitochondria

### ISSUE THREAD

**Issue by rob123king** [NBISweden/EMBLmyGFF3#52]
I have a translation table of 4 for mitochondria but when create embl file it says there is a conflict between species translation table 1, how do I set organelle to get round this?

organelle = self._verify( self.organelle, "organelle")
AttributeError: 'EMBL' object has no attribute 'organelle'

**Comment by Juke34** [comment]
What command did yo run?
Can you run it with more verbosity to see where the problem comes from?

**Comment by rob123king** [comment]
EMBLmyGFF3 FC_Mitochondria2.gff FC_Mitochondria.fasta --topology circular --molecule_type 'genomic DNA' --species 'Fusarium culmorum' --project_id PRJEB36692 -o FC_Mitochondria.embl -g Mitochondrion

Without the -g option. It works fine but then when I validate I get the below error, even when change the embl DE line to Mitchondrion
ERROR: organism classified. Submitted /transl_table "4" conflicts with translation table "1" recruited from taxonomy. Please check submitted /transl_table, /organelle and /organism for agreement. Contact us if necessary. [ line: 1 of FC_Mitochondria.embl.gz]

**Comment by Juke34** [comment]
The problem comes that your EMBL file created with EMBLmyGFF3 contains the information to use the table4 (what is correct as it is mitochondrial genome) while the ENA check sees that the organism is Fusarium culmorum and should have table 1. It sounds they don't deal properly with the information that you are submitting the organelle of this organism.
I'm not sure there is anything we can do from EMBLmyGFF3 side. Maybe there is a way by modifying the DE line as you tried but I'm not sure. You should contact the ENA Helpdesk to see what is the correct way to deal with that. 
Come back to use If there is anything we could then implement to avoid this problem.

**Comment by Juke34** [comment]
I report here what we discuss on biostars (https://www.biostars.org/p/435707/#436088)
The name of the chromosome in the AC line is extracted from the fasta file by EMBLmyGFF3. It should be the same as the OBJECT_NAME (first column) you specify within the the chromosome list file.

Since version 2.2.3 webin-cli requires a manifest file and a chromosome list that are formatted according to the below guidelines:

Manifest file guidance: https://ena-docs.readthedocs.io/en/latest/submit/assembly/genome.html# manifest-files

Chromosome list file guidance: https://ena-docs.readthedocs.io/en/latest/submit/fileprep/assembly.html# chromosome-list-file
